### PR TITLE
Inf fix

### PR DESCRIPTION
**Pull request by vayner-s**
Fixing the infinite error problem when no ignition found.

### CODE REVIEW

**Comment by rwest** [comment]
Umm, somehow the pull request has 45 commits not two (or one - you could easily squash your second as a fixup).

Please can you rebase (or interactive rebase to squash your commits together)  onto the master branch?

**Comment by vayner-s** [comment]
Yeah, I'll change that. It's because I originally pulled from the prometheus version which is ahead of the comocheng one.

**Comment by rwest** [comment]
didn't need to close the pull request. Could rebase then force-push to the same branch and it'll update the PR. (could still do so, if you reopen this one)

**Comment by vayner-s** [comment]
I was going to just merge into master locally, reset my master to origin, make the change a single commit, and then push to master to make things simpler, if that works?

**Comment by vayner-s** [comment]
The simulaiton.py file that I'm making the change in is significantly different when I revert it back to the comocheng version so  I'm not sure if it makes sense to wait until comocheng is up to date with prometheus before pushing it. It seems like the fix would still work on the old version but I'm not 100% sure as I've only tested it on the prometheus version. That's the version I used for Eric's model as well.

**Comment by rwest** [comment]
We should probably be up to date with Prometheus. Why do we need to use an out of date version?

**Comment by vayner-s** [comment]
Yeah, I'm saying that since I'm PRing the change into the comocheng repo, I had to revert my local master to the comocheng master because comocheng is currently behind prometheus. That's where the other 43 commits were coming from. I was trying to ask if we should get the comocheng repo up to date with prometheus before I push?

**Comment by rwest** [comment]
Ah, I see. Sorry I was confused. Yes, get the comecheng master up to date. But also, I suggest opening your PR aganist the prometheus master.

**Comment by vayner-s** [comment]
Once comocheng is up to date, would it make sense for me to just push directly to comocheng master and then make a PR from comocheng to prometheus?

**Comment by rwest** [comment]
I wouldn't make a PR from master, because you never know when the PR will actually get merged, and what else will happen on Master in that time. Use a topic branch. Whether it's on comocheng or on vayner-s is the question. Either is OK. Benefit of comocheng is that other people (like me) can more easily update / fix / maintain / rebase.

**Comment by vayner-s** [comment]
Ok, so useing the inf_fix branch from comocheng but PRing directly into prometheus master instead of merging into comocheng master would work then?

**Pull request closed without merging**
